name: task_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.1



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider:


flutter:

  uses-material-design: true

